stages:          # List of stages for jobs, and their order of execution
  - build
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

image: maven:3.9.9-eclipse-temurin-25

cache:
  paths:
    - .m2/repository
  key: "$CI_COMMIT_REF_SLUG"


build:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - 'mvn compile'

test:
  stage: test
  coverage: '/Total.*?([0-9]{1,3})%/'
  script:
    - 'mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent test jacoco:report'
    - '[ -f target/site/jacoco/index.html ] && sed -E -e "s;^.*Total[^%]*>([0-9]+%)<.*$;Total Coverage: \\1\\n;g" target/site/jacoco/index.html'
  artifacts:
    reports:
      coverage_report:
        coverage_format: jacoco
        path: target/site/jacoco/jacoco.xml
        

